using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// 爻y计qゅr
/// </summary>
public class BuildCountText : MonoBehaviour
{
    //Conponent
    Text thisText;
    Transform targetObject;//ヘ夹ン    

    //爻y计q
    int currentCount;//ヘe计q
    const int completeCount = 100;//爻yЧΘ计q
    const int addScore = 100;//[だ

    private void Awake()
    {
        thisText = GetComponent<Text>();       

        //ゅr
        thisText.text = currentCount + "/" + completeCount;//爻yЧΘ计q
    }

    private void Update()
    {
        OnPosition();//だ计旄m
    }

    /// <summary>
    /// ]wヘ夹
    /// </summary>
    public Transform SetTarget { set { targetObject = value; } }

    /// <summary>
    /// W[だ计
    /// </summary>
    public void OnSetScore()
    {
        currentCount++;//ヘe计qW[

        //ЧΘ爻y计q
        if (currentCount == completeCount)
        {
            currentCount = 0;
            GameManagement.Instance.currentScore += addScore;//[だ
            GameManagement.Instance.score_Text.text = $"だ计: {GameManagement.Instance.currentScore}";
        }

        //ゅr
        thisText.text = currentCount + "/" + completeCount;        
    }

    /// <summary>
    /// 旄m
    /// </summary>
    void OnPosition()
    {
        if (targetObject == null) return;

        //旄m
        Vector3 position = Camera.main.WorldToScreenPoint(targetObject.position);
        transform.position = position;
    }
}
