using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// だ计ゅr
/// </summary>
public class ScoreText : MonoBehaviour
{
    //Conponent
    Text thisText;
    Transform targetObject;//ヘ夹ン

    //ゅr
    int score;//だ计
    const int fullScore = 100;//骸だ

    private void Awake()
    {
        thisText = GetComponent<Text>();

        thisText.text = score + "/" + fullScore;
    }

    private void Update()
    {
        OnScorePosition();//だ计旄m
    }

    /// <summary>
    /// ]wヘ夹
    /// </summary>
    public Transform SetTarget { set { targetObject = value; } }

    /// <summary>
    /// W[だ计
    /// </summary>
    public void OnSetScore()
    {
        score++;//だ计W[

        //ゅr
        thisText.text = score + "/" + fullScore;
    }

    /// <summary>
    /// だ计旄m
    /// </summary>
    void OnScorePosition()
    {
        if (targetObject == null) return;

        //旄m
        Vector3 position = Camera.main.WorldToScreenPoint(targetObject.position);
        transform.position = position;
    }
}
